apiVersion: v1
kind: Service
metadata:
  name: xpert-sankhia-mongo-loadbalancer
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: xpertsankhiastatefulset-0
  ports:
  - port: 4411
    targetPort: 27017
