apiVersion: v1
kind: Service
metadata:
  labels:
    app: xpertsankhiaheadlessservice
  name: xpertsankhiaheadlessservice
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: xpertsankhiastatefulset
  sessionAffinity: None
  type: ClusterIP
